name: Get Random Dailymotion Video

on:
  workflow_dispatch:

jobs:
  fetch_video:
    runs-on: ubuntu-latest
    steps:
      - name: Get Random Dailymotion Video
        run: |
          VIDEO_URL=$(curl -s "https://api.dailymotion.com/videos?fields=url&limit=1&sort=random" | jq -r '.list[0].url')
          echo "Random Dailymotion Video URL: $VIDEO_URL"
